/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v100.0.100
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DataIntegrityProofOptions,
  DataIntegrityProofOptionsFromJSON,
  DataIntegrityProofOptionsFromJSONTyped,
  DataIntegrityProofOptionsToJSON,
} from './';

/**
 *
 * @export
 * @interface AddProof
 */
export interface AddProof {
  /**
   *
   * @type {object}
   * @memberof AddProof
   */
  document: object;
  /**
   *
   * @type {DataIntegrityProofOptions}
   * @memberof AddProof
   */
  options?: DataIntegrityProofOptions;
}

export function AddProofFromJSON(json: any): AddProof {
  return AddProofFromJSONTyped(json, false);
}

export function AddProofFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddProof {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    document: json['document'],
    options: !exists(json, 'options')
      ? undefined
      : DataIntegrityProofOptionsFromJSON(json['options']),
  };
}

export function AddProofToJSON(value?: AddProof | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    document: value.document,
    options: DataIntegrityProofOptionsToJSON(value.options),
  };
}
