/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AnonCredsRequestedCredsRequestedAttr,
  AnonCredsRequestedCredsRequestedAttrFromJSON,
  AnonCredsRequestedCredsRequestedAttrFromJSONTyped,
  AnonCredsRequestedCredsRequestedAttrToJSON,
  AnonCredsRequestedCredsRequestedPred,
  AnonCredsRequestedCredsRequestedPredFromJSON,
  AnonCredsRequestedCredsRequestedPredFromJSONTyped,
  AnonCredsRequestedCredsRequestedPredToJSON,
} from './';

/**
 *
 * @export
 * @interface AnonCredsPresSpec
 */
export interface AnonCredsPresSpec {
  /**
   * Nested object mapping proof request attribute referents to requested-attribute specifiers
   * @type {{ [key: string]: AnonCredsRequestedCredsRequestedAttr; }}
   * @memberof AnonCredsPresSpec
   */
  requested_attributes: { [key: string]: AnonCredsRequestedCredsRequestedAttr };
  /**
   * Nested object mapping proof request predicate referents to requested-predicate specifiers
   * @type {{ [key: string]: AnonCredsRequestedCredsRequestedPred; }}
   * @memberof AnonCredsPresSpec
   */
  requested_predicates: { [key: string]: AnonCredsRequestedCredsRequestedPred };
  /**
   * Self-attested attributes to build into proof
   * @type {{ [key: string]: string; }}
   * @memberof AnonCredsPresSpec
   */
  self_attested_attributes: { [key: string]: string };
  /**
   * Whether to trace event (default false)
   * @type {boolean}
   * @memberof AnonCredsPresSpec
   */
  trace?: boolean;
}

export function AnonCredsPresSpecFromJSON(json: any): AnonCredsPresSpec {
  return AnonCredsPresSpecFromJSONTyped(json, false);
}

export function AnonCredsPresSpecFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnonCredsPresSpec {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    requested_attributes: mapValues(
      json['requested_attributes'],
      AnonCredsRequestedCredsRequestedAttrFromJSON,
    ),
    requested_predicates: mapValues(
      json['requested_predicates'],
      AnonCredsRequestedCredsRequestedPredFromJSON,
    ),
    self_attested_attributes: json['self_attested_attributes'],
    trace: !exists(json, 'trace') ? undefined : json['trace'],
  };
}

export function AnonCredsPresSpecToJSON(value?: AnonCredsPresSpec | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    requested_attributes: mapValues(
      value.requested_attributes,
      AnonCredsRequestedCredsRequestedAttrToJSON,
    ),
    requested_predicates: mapValues(
      value.requested_predicates,
      AnonCredsRequestedCredsRequestedPredToJSON,
    ),
    self_attested_attributes: value.self_attested_attributes,
    trace: value.trace,
  };
}
