/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AnoncredsPresentationReqAttrSpec,
  AnoncredsPresentationReqAttrSpecFromJSON,
  AnoncredsPresentationReqAttrSpecFromJSONTyped,
  AnoncredsPresentationReqAttrSpecToJSON,
  AnoncredsPresentationReqPredSpec,
  AnoncredsPresentationReqPredSpecFromJSON,
  AnoncredsPresentationReqPredSpecFromJSONTyped,
  AnoncredsPresentationReqPredSpecToJSON,
  AnoncredsPresentationRequestNonRevoked,
  AnoncredsPresentationRequestNonRevokedFromJSON,
  AnoncredsPresentationRequestNonRevokedFromJSONTyped,
  AnoncredsPresentationRequestNonRevokedToJSON,
} from './';

/**
 *
 * @export
 * @interface AnoncredsPresentationRequest
 */
export interface AnoncredsPresentationRequest {
  /**
   * Proof request name
   * @type {string}
   * @memberof AnoncredsPresentationRequest
   */
  name?: string;
  /**
   *
   * @type {AnoncredsPresentationRequestNonRevoked}
   * @memberof AnoncredsPresentationRequest
   */
  non_revoked?: AnoncredsPresentationRequestNonRevoked;
  /**
   * Nonce
   * @type {string}
   * @memberof AnoncredsPresentationRequest
   */
  nonce?: string;
  /**
   * Requested attribute specifications of proof request
   * @type {{ [key: string]: AnoncredsPresentationReqAttrSpec; }}
   * @memberof AnoncredsPresentationRequest
   */
  requested_attributes: { [key: string]: AnoncredsPresentationReqAttrSpec };
  /**
   * Requested predicate specifications of proof request
   * @type {{ [key: string]: AnoncredsPresentationReqPredSpec; }}
   * @memberof AnoncredsPresentationRequest
   */
  requested_predicates: { [key: string]: AnoncredsPresentationReqPredSpec };
  /**
   * Proof request version
   * @type {string}
   * @memberof AnoncredsPresentationRequest
   */
  version?: string;
}

export function AnoncredsPresentationRequestFromJSON(
  json: any,
): AnoncredsPresentationRequest {
  return AnoncredsPresentationRequestFromJSONTyped(json, false);
}

export function AnoncredsPresentationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnoncredsPresentationRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    non_revoked: !exists(json, 'non_revoked')
      ? undefined
      : AnoncredsPresentationRequestNonRevokedFromJSON(json['non_revoked']),
    nonce: !exists(json, 'nonce') ? undefined : json['nonce'],
    requested_attributes: mapValues(
      json['requested_attributes'],
      AnoncredsPresentationReqAttrSpecFromJSON,
    ),
    requested_predicates: mapValues(
      json['requested_predicates'],
      AnoncredsPresentationReqPredSpecFromJSON,
    ),
    version: !exists(json, 'version') ? undefined : json['version'],
  };
}

export function AnoncredsPresentationRequestToJSON(
  value?: AnoncredsPresentationRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    non_revoked: AnoncredsPresentationRequestNonRevokedToJSON(
      value.non_revoked,
    ),
    nonce: value.nonce,
    requested_attributes: mapValues(
      value.requested_attributes,
      AnoncredsPresentationReqAttrSpecToJSON,
    ),
    requested_predicates: mapValues(
      value.requested_predicates,
      AnoncredsPresentationReqPredSpecToJSON,
    ),
    version: value.version,
  };
}
