/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AnonCredsRequestedCredsRequestedAttr
 */
export interface AnonCredsRequestedCredsRequestedAttr {
  /**
   * Wallet credential identifier (typically but not necessarily a UUID)
   * @type {string}
   * @memberof AnonCredsRequestedCredsRequestedAttr
   */
  cred_id: string;
  /**
   * Whether to reveal attribute in proof (default true)
   * @type {boolean}
   * @memberof AnonCredsRequestedCredsRequestedAttr
   */
  revealed?: boolean;
}

export function AnonCredsRequestedCredsRequestedAttrFromJSON(
  json: any,
): AnonCredsRequestedCredsRequestedAttr {
  return AnonCredsRequestedCredsRequestedAttrFromJSONTyped(json, false);
}

export function AnonCredsRequestedCredsRequestedAttrFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnonCredsRequestedCredsRequestedAttr {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cred_id: json['cred_id'],
    revealed: !exists(json, 'revealed') ? undefined : json['revealed'],
  };
}

export function AnonCredsRequestedCredsRequestedAttrToJSON(
  value?: AnonCredsRequestedCredsRequestedAttr | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cred_id: value.cred_id,
    revealed: value.revealed,
  };
}
