/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AnoncredsPresentationReqPredSpecNonRevoked,
  AnoncredsPresentationReqPredSpecNonRevokedFromJSON,
  AnoncredsPresentationReqPredSpecNonRevokedFromJSONTyped,
  AnoncredsPresentationReqPredSpecNonRevokedToJSON,
} from './';

/**
 *
 * @export
 * @interface AnoncredsPresentationReqPredSpec
 */
export interface AnoncredsPresentationReqPredSpec {
  /**
   * Attribute name
   * @type {string}
   * @memberof AnoncredsPresentationReqPredSpec
   */
  name: string;
  /**
   *
   * @type {AnoncredsPresentationReqPredSpecNonRevoked}
   * @memberof AnoncredsPresentationReqPredSpec
   */
  non_revoked?: AnoncredsPresentationReqPredSpecNonRevoked;
  /**
   * Predicate type ('<', '<=', '>=', or '>')
   * @type {string}
   * @memberof AnoncredsPresentationReqPredSpec
   */
  p_type: AnoncredsPresentationReqPredSpecPTypeEnum;
  /**
   * Threshold value
   * @type {number}
   * @memberof AnoncredsPresentationReqPredSpec
   */
  p_value: number;
  /**
   * If present, credential must satisfy one of given restrictions: specify schema_id, schema_issuer_did, schema_name, schema_version, issuer_did, cred_def_id, and/or attr::<attribute-name>::value where <attribute-name> represents a credential attribute name
   * @type {Array<{ [key: string]: string; }>}
   * @memberof AnoncredsPresentationReqPredSpec
   */
  restrictions?: Array<{ [key: string]: string }>;
}

/**
 * @export
 * @enum {string}
 */
export enum AnoncredsPresentationReqPredSpecPTypeEnum {
  LessThan = '<',
  LessThanOrEqualTo = '<=',
  GreaterThanOrEqualTo = '>=',
  GreaterThan = '>',
}

export function AnoncredsPresentationReqPredSpecFromJSON(
  json: any,
): AnoncredsPresentationReqPredSpec {
  return AnoncredsPresentationReqPredSpecFromJSONTyped(json, false);
}

export function AnoncredsPresentationReqPredSpecFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnoncredsPresentationReqPredSpec {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    non_revoked: !exists(json, 'non_revoked')
      ? undefined
      : AnoncredsPresentationReqPredSpecNonRevokedFromJSON(json['non_revoked']),
    p_type: json['p_type'],
    p_value: json['p_value'],
    restrictions: !exists(json, 'restrictions')
      ? undefined
      : json['restrictions'],
  };
}

export function AnoncredsPresentationReqPredSpecToJSON(
  value?: AnoncredsPresentationReqPredSpec | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    non_revoked: AnoncredsPresentationReqPredSpecNonRevokedToJSON(
      value.non_revoked,
    ),
    p_type: value.p_type,
    p_value: value.p_value,
    restrictions: value.restrictions,
  };
}
