/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MaybeStoredConnectionsRecord,
  MaybeStoredConnectionsRecordFromJSON,
  MaybeStoredConnectionsRecordFromJSONTyped,
  MaybeStoredConnectionsRecordToJSON,
} from './';

/**
 *
 * @export
 * @interface ConnectionListV1
 */
export interface ConnectionListV1 {
  /**
   * List of connection records
   * @type {Array<MaybeStoredConnectionsRecord>}
   * @memberof ConnectionListV1
   */
  results: Array<MaybeStoredConnectionsRecord>;
}

export function ConnectionListV1FromJSON(json: any): ConnectionListV1 {
  return ConnectionListV1FromJSONTyped(json, false);
}

export function ConnectionListV1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConnectionListV1 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    results: (json['results'] as Array<any>).map(
      MaybeStoredConnectionsRecordFromJSON,
    ),
  };
}

export function ConnectionListV1ToJSON(value?: ConnectionListV1 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    results: (value.results as Array<any>).map(
      MaybeStoredConnectionsRecordToJSON,
    ),
  };
}
