/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MaybeStoredConnectionsRecord,
  MaybeStoredConnectionsRecordFromJSON,
  MaybeStoredConnectionsRecordFromJSONTyped,
  MaybeStoredConnectionsRecordToJSON,
} from './';

/**
 *
 * @export
 * @interface ConnectionStaticResultV1
 */
export interface ConnectionStaticResultV1 {
  /**
   * Local DID
   * @type {string}
   * @memberof ConnectionStaticResultV1
   */
  my_did: string;
  /**
   * My URL endpoint
   * @type {string}
   * @memberof ConnectionStaticResultV1
   */
  my_endpoint: string;
  /**
   * My verification key
   * @type {string}
   * @memberof ConnectionStaticResultV1
   */
  my_verkey: string;
  /**
   *
   * @type {MaybeStoredConnectionsRecord}
   * @memberof ConnectionStaticResultV1
   */
  record: MaybeStoredConnectionsRecord;
  /**
   * Remote DID
   * @type {string}
   * @memberof ConnectionStaticResultV1
   */
  their_did: string;
  /**
   * Remote verification key
   * @type {string}
   * @memberof ConnectionStaticResultV1
   */
  their_verkey: string;
}

export function ConnectionStaticResultV1FromJSON(
  json: any,
): ConnectionStaticResultV1 {
  return ConnectionStaticResultV1FromJSONTyped(json, false);
}

export function ConnectionStaticResultV1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConnectionStaticResultV1 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    my_did: json['my_did'],
    my_endpoint: json['my_endpoint'],
    my_verkey: json['my_verkey'],
    record: MaybeStoredConnectionsRecordFromJSON(json['record']),
    their_did: json['their_did'],
    their_verkey: json['their_verkey'],
  };
}

export function ConnectionStaticResultV1ToJSON(
  value?: ConnectionStaticResultV1 | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    my_did: value.my_did,
    my_endpoint: value.my_endpoint,
    my_verkey: value.my_verkey,
    record: MaybeStoredConnectionsRecordToJSON(value.record),
    their_did: value.their_did,
    their_verkey: value.their_verkey,
  };
}
