/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateDidIndyRequest
 */
export interface CreateDidIndyRequest {
  /**
   * Additional features to enable for the did.
   * @type {{ [key: string]: object; }}
   * @memberof CreateDidIndyRequest
   */
  features?: { [key: string]: object };
  /**
   * Additional configuration options. Supported options: did, seed, key_type. Default key_type is ed25519.
   * @type {{ [key: string]: object; }}
   * @memberof CreateDidIndyRequest
   */
  options?: { [key: string]: object };
}

export function CreateDidIndyRequestFromJSON(json: any): CreateDidIndyRequest {
  return CreateDidIndyRequestFromJSONTyped(json, false);
}

export function CreateDidIndyRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDidIndyRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    features: !exists(json, 'features') ? undefined : json['features'],
    options: !exists(json, 'options') ? undefined : json['options'],
  };
}

export function CreateDidIndyRequestToJSON(
  value?: CreateDidIndyRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    features: value.features,
    options: value.options,
  };
}
