/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateRequest
 */
export interface CreateRequest {
  /**
   * Additional features to enable for the did.
   * @type {{ [key: string]: object; }}
   * @memberof CreateRequest
   */
  features?: { [key: string]: object };
  /**
   * Additional configuration options
   * @type {{ [key: string]: object; }}
   * @memberof CreateRequest
   */
  options?: { [key: string]: object };
}

export function CreateRequestFromJSON(json: any): CreateRequest {
  return CreateRequestFromJSONTyped(json, false);
}

export function CreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    features: !exists(json, 'features') ? undefined : json['features'],
    options: !exists(json, 'options') ? undefined : json['options'],
  };
}

export function CreateRequestToJSON(value?: CreateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    features: value.features,
    options: value.options,
  };
}
