/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.10.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateOID4VPPresDefResponse
 */
export interface CreateOID4VPPresDefResponse {
  /**
   *
   * @type {object}
   * @memberof CreateOID4VPPresDefResponse
   */
  pres_def: object;
}

export function CreateOID4VPPresDefResponseFromJSON(
  json: any,
): CreateOID4VPPresDefResponse {
  return CreateOID4VPPresDefResponseFromJSONTyped(json, false);
}

export function CreateOID4VPPresDefResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOID4VPPresDefResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    pres_def: json['pres_def'],
  };
}

export function CreateOID4VPPresDefResponseToJSON(
  value?: CreateOID4VPPresDefResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    pres_def: value.pres_def,
  };
}
