/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  CredOffer,
  CredOfferFromJSON,
  CredOfferFromJSONTyped,
  CredOfferToJSON,
} from './';

/**
 *
 * @export
 * @interface CredOfferResponseSchemaVal
 */
export interface CredOfferResponseSchemaVal {
  /**
   * The URL of the credential value for display by QR code.
   * @type {string}
   * @memberof CredOfferResponseSchemaVal
   */
  credential_offer: string;
  /**
   *
   * @type {CredOffer}
   * @memberof CredOfferResponseSchemaVal
   */
  offer: CredOffer;
}

export function CredOfferResponseSchemaValFromJSON(
  json: any,
): CredOfferResponseSchemaVal {
  return CredOfferResponseSchemaValFromJSONTyped(json, false);
}

export function CredOfferResponseSchemaValFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CredOfferResponseSchemaVal {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    credential_offer: json['credential_offer'],
    offer: CredOfferFromJSON(json['offer']),
  };
}

export function CredOfferResponseSchemaValToJSON(
  value?: CredOfferResponseSchemaVal | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    credential_offer: value.credential_offer,
    offer: CredOfferToJSON(value.offer),
  };
}
