/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeactivateRequest
 */
export interface DeactivateRequest {
  /**
   * DID to deactivate
   * @type {string}
   * @memberof DeactivateRequest
   */
  did: string;
  /**
   * Additional configuration options
   * @type {{ [key: string]: object; }}
   * @memberof DeactivateRequest
   */
  options?: { [key: string]: object };
}

export function DeactivateRequestFromJSON(json: any): DeactivateRequest {
  return DeactivateRequestFromJSONTyped(json, false);
}

export function DeactivateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeactivateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    did: json['did'],
    options: !exists(json, 'options') ? undefined : json['options'],
  };
}

export function DeactivateRequestToJSON(value?: DeactivateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    did: value.did,
    options: value.options,
  };
}
