/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeactivateCheqdDIDResponse
 */
export interface DeactivateCheqdDIDResponse {
  /**
   * DID that has been deactivated
   * @type {string}
   * @memberof DeactivateCheqdDIDResponse
   */
  did?: string;
  /**
   * State of the did update
   * @type {string}
   * @memberof DeactivateCheqdDIDResponse
   */
  didState: string;
  /**
   * Flag to denote if the operation was successful
   * @type {boolean}
   * @memberof DeactivateCheqdDIDResponse
   */
  success?: boolean;
}

export function DeactivateCheqdDIDResponseFromJSON(
  json: any,
): DeactivateCheqdDIDResponse {
  return DeactivateCheqdDIDResponseFromJSONTyped(json, false);
}

export function DeactivateCheqdDIDResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeactivateCheqdDIDResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    did: !exists(json, 'did') ? undefined : json['did'],
    didState: json['didState'],
    success: !exists(json, 'success') ? undefined : json['success'],
  };
}

export function DeactivateCheqdDIDResponseToJSON(
  value?: DeactivateCheqdDIDResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    did: value.did,
    didState: value.didState,
    success: value.success,
  };
}
