/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DIDRotateRequestJSON
 */
export interface DIDRotateRequestJSON {
  /**
   * The DID the rotating party is rotating to
   * @type {string}
   * @memberof DIDRotateRequestJSON
   */
  to_did: string;
}

export function DIDRotateRequestJSONFromJSON(json: any): DIDRotateRequestJSON {
  return DIDRotateRequestJSONFromJSONTyped(json, false);
}

export function DIDRotateRequestJSONFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DIDRotateRequestJSON {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    to_did: json['to_did'],
  };
}

export function DIDRotateRequestJSONToJSON(
  value?: DIDRotateRequestJSON | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    to_did: value.to_did,
  };
}
