/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DIDXRejectRequest
 */
export interface DIDXRejectRequest {
  /**
   * Reason for rejecting the DID Exchange
   * @type {string}
   * @memberof DIDXRejectRequest
   */
  reason?: string;
}

export function DIDXRejectRequestFromJSON(json: any): DIDXRejectRequest {
  return DIDXRejectRequestFromJSONTyped(json, false);
}

export function DIDXRejectRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DIDXRejectRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    reason: !exists(json, 'reason') ? undefined : json['reason'],
  };
}

export function DIDXRejectRequestToJSON(value?: DIDXRejectRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    reason: value.reason,
  };
}
