/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExchangeRecordCreateRequest
 */
export interface ExchangeRecordCreateRequest {
  /**
   * desired claim and value in credential
   * @type {{ [key: string]: object; }}
   * @memberof ExchangeRecordCreateRequest
   */
  credential_subject: { [key: string]: object };
  /**
   * DID of interest
   * @type {string}
   * @memberof ExchangeRecordCreateRequest
   */
  did?: string;
  /**
   * User PIN sent out of band to the user.
   * @type {string}
   * @memberof ExchangeRecordCreateRequest
   */
  pin?: string;
  /**
   * Identifier used to identify credential supported record
   * @type {string}
   * @memberof ExchangeRecordCreateRequest
   */
  supported_cred_id: string;
  /**
   * Information used for proof verification
   * @type {string}
   * @memberof ExchangeRecordCreateRequest
   */
  verification_method?: string;
}

export function ExchangeRecordCreateRequestFromJSON(
  json: any,
): ExchangeRecordCreateRequest {
  return ExchangeRecordCreateRequestFromJSONTyped(json, false);
}

export function ExchangeRecordCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExchangeRecordCreateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    credential_subject: json['credential_subject'],
    did: !exists(json, 'did') ? undefined : json['did'],
    pin: !exists(json, 'pin') ? undefined : json['pin'],
    supported_cred_id: json['supported_cred_id'],
    verification_method: !exists(json, 'verification_method')
      ? undefined
      : json['verification_method'],
  };
}

export function ExchangeRecordCreateRequestToJSON(
  value?: ExchangeRecordCreateRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    credential_subject: value.credential_subject,
    did: value.did,
    pin: value.pin,
    supported_cred_id: value.supported_cred_id,
    verification_method: value.verification_method,
  };
}
