/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  CredentialQuery,
  CredentialQueryFromJSON,
  CredentialQueryFromJSONTyped,
  CredentialQueryToJSON,
  CredentialSetQuery,
  CredentialSetQueryFromJSON,
  CredentialSetQueryFromJSONTyped,
  CredentialSetQueryToJSON,
} from './';

/**
 *
 * @export
 * @interface GetDCQLQueryResponse
 */
export interface GetDCQLQueryResponse {
  /**
   * A list of credential set query objects
   * @type {Array<CredentialSetQuery>}
   * @memberof GetDCQLQueryResponse
   */
  credential_sets?: Array<CredentialSetQuery>;
  /**
   * A list of credential query objects
   * @type {Array<CredentialQuery>}
   * @memberof GetDCQLQueryResponse
   */
  credentials: Array<CredentialQuery>;
  /**
   * Query identifier
   * @type {string}
   * @memberof GetDCQLQueryResponse
   */
  dcql_query_id: string;
}

export function GetDCQLQueryResponseFromJSON(json: any): GetDCQLQueryResponse {
  return GetDCQLQueryResponseFromJSONTyped(json, false);
}

export function GetDCQLQueryResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDCQLQueryResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    credential_sets: !exists(json, 'credential_sets')
      ? undefined
      : (json['credential_sets'] as Array<any>).map(CredentialSetQueryFromJSON),
    credentials: (json['credentials'] as Array<any>).map(
      CredentialQueryFromJSON,
    ),
    dcql_query_id: json['dcql_query_id'],
  };
}

export function GetDCQLQueryResponseToJSON(
  value?: GetDCQLQueryResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    credential_sets:
      value.credential_sets === undefined
        ? undefined
        : (value.credential_sets as Array<any>).map(CredentialSetQueryToJSON),
    credentials: (value.credentials as Array<any>).map(CredentialQueryToJSON),
    dcql_query_id: value.dcql_query_id,
  };
}
