/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.6.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  IndyProofReqAttrSpec,
  IndyProofReqAttrSpecFromJSON,
  IndyProofReqAttrSpecFromJSONTyped,
  IndyProofReqAttrSpecToJSON,
  IndyProofReqPredSpec,
  IndyProofReqPredSpecFromJSON,
  IndyProofReqPredSpecFromJSONTyped,
  IndyProofReqPredSpecToJSON,
  IndyProofRequestNonRevoked,
  IndyProofRequestNonRevokedFromJSON,
  IndyProofRequestNonRevokedFromJSONTyped,
  IndyProofRequestNonRevokedToJSON,
} from './';

/**
 *
 * @export
 * @interface IndyProofRequest
 */
export interface IndyProofRequest {
  /**
   * Proof request name
   * @type {string}
   * @memberof IndyProofRequest
   */
  name?: string;
  /**
   *
   * @type {IndyProofRequestNonRevoked}
   * @memberof IndyProofRequest
   */
  non_revoked?: IndyProofRequestNonRevoked | null;
  /**
   * Nonce
   * @type {string}
   * @memberof IndyProofRequest
   */
  nonce?: string;
  /**
   * Requested attribute specifications of proof request
   * @type {{ [key: string]: IndyProofReqAttrSpec; }}
   * @memberof IndyProofRequest
   */
  requested_attributes: { [key: string]: IndyProofReqAttrSpec };
  /**
   * Requested predicate specifications of proof request
   * @type {{ [key: string]: IndyProofReqPredSpec; }}
   * @memberof IndyProofRequest
   */
  requested_predicates: { [key: string]: IndyProofReqPredSpec };
  /**
   * Proof request version
   * @type {string}
   * @memberof IndyProofRequest
   */
  version?: string;
}

export function IndyProofRequestFromJSON(json: any): IndyProofRequest {
  return IndyProofRequestFromJSONTyped(json, false);
}

export function IndyProofRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IndyProofRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    non_revoked: !exists(json, 'non_revoked')
      ? undefined
      : IndyProofRequestNonRevokedFromJSON(json['non_revoked']),
    nonce: !exists(json, 'nonce') ? undefined : json['nonce'],
    requested_attributes: mapValues(
      json['requested_attributes'],
      IndyProofReqAttrSpecFromJSON,
    ),
    requested_predicates: mapValues(
      json['requested_predicates'],
      IndyProofReqPredSpecFromJSON,
    ),
    version: !exists(json, 'version') ? undefined : json['version'],
  };
}

export function IndyProofRequestToJSON(value?: IndyProofRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    non_revoked: IndyProofRequestNonRevokedToJSON(value.non_revoked),
    nonce: value.nonce,
    requested_attributes: mapValues(
      value.requested_attributes,
      IndyProofReqAttrSpecToJSON,
    ),
    requested_predicates: mapValues(
      value.requested_predicates,
      IndyProofReqPredSpecToJSON,
    ),
    version: value.version,
  };
}
