/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agency Service
 *
 * The version of the OpenAPI document: v0.5.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  IndyProofReqPredSpecNonRevoked,
  IndyProofReqPredSpecNonRevokedFromJSON,
  IndyProofReqPredSpecNonRevokedFromJSONTyped,
  IndyProofReqPredSpecNonRevokedToJSON,
} from './';

/**
 *
 * @export
 * @interface IndyProofReqPredSpec
 */
export interface IndyProofReqPredSpec {
  /**
   * Attribute name
   * @type {string}
   * @memberof IndyProofReqPredSpec
   */
  name: string;
  /**
   *
   * @type {IndyProofReqPredSpecNonRevoked}
   * @memberof IndyProofReqPredSpec
   */
  non_revoked?: IndyProofReqPredSpecNonRevoked | null;
  /**
   * Predicate type ('<', '<=', '>=', or '>')
   * @type {string}
   * @memberof IndyProofReqPredSpec
   */
  p_type: IndyProofReqPredSpecPTypeEnum;
  /**
   * Threshold value
   * @type {number}
   * @memberof IndyProofReqPredSpec
   */
  p_value: number;
  /**
   * If present, credential must satisfy one of given restrictions: specify schema_id, schema_issuer_did, schema_name, schema_version, issuer_did, cred_def_id, and/or attr::<attribute-name>::value where <attribute-name> represents a credential attribute name
   * @type {Array<{ [key: string]: string; }>}
   * @memberof IndyProofReqPredSpec
   */
  restrictions?: Array<{ [key: string]: string }>;
}

/**
 * @export
 * @enum {string}
 */
export enum IndyProofReqPredSpecPTypeEnum {
  LessThan = '<',
  LessThanOrEqualTo = '<=',
  GreaterThanOrEqualTo = '>=',
  GreaterThan = '>',
}

export function IndyProofReqPredSpecFromJSON(json: any): IndyProofReqPredSpec {
  return IndyProofReqPredSpecFromJSONTyped(json, false);
}

export function IndyProofReqPredSpecFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IndyProofReqPredSpec {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    non_revoked: !exists(json, 'non_revoked')
      ? undefined
      : IndyProofReqPredSpecNonRevokedFromJSON(json['non_revoked']),
    p_type: json['p_type'],
    p_value: json['p_value'],
    restrictions: !exists(json, 'restrictions')
      ? undefined
      : json['restrictions'],
  };
}

export function IndyProofReqPredSpecToJSON(
  value?: IndyProofReqPredSpec | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    non_revoked: IndyProofReqPredSpecNonRevokedToJSON(value.non_revoked),
    p_type: value.p_type,
    p_value: value.p_value,
    restrictions: value.restrictions,
  };
}
