/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MediationIdMatchInfo
 */
export interface MediationIdMatchInfo {
  /**
   * Mediation record identifier
   * @type {string}
   * @memberof MediationIdMatchInfo
   */
  mediation_id: string;
}

export function MediationIdMatchInfoFromJSON(json: any): MediationIdMatchInfo {
  return MediationIdMatchInfoFromJSONTyped(json, false);
}

export function MediationIdMatchInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MediationIdMatchInfo {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    mediation_id: json['mediation_id'],
  };
}

export function MediationIdMatchInfoToJSON(
  value?: MediationIdMatchInfo | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    mediation_id: value.mediation_id,
  };
}
