/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PublishStatusListResponse
 */
export interface PublishStatusListResponse {
  /**
   * Status list definition id.
   * @type {string}
   * @memberof PublishStatusListResponse
   */
  definition_id: string;
  /**
   * Error text
   * @type {string}
   * @memberof PublishStatusListResponse
   */
  error?: string;
  /**
   *
   * @type {boolean}
   * @memberof PublishStatusListResponse
   */
  published: boolean;
  /**
   * Published status lists.
   * @type {Array<string>}
   * @memberof PublishStatusListResponse
   */
  status_lists?: Array<string>;
}

export function PublishStatusListResponseFromJSON(
  json: any,
): PublishStatusListResponse {
  return PublishStatusListResponseFromJSONTyped(json, false);
}

export function PublishStatusListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PublishStatusListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    definition_id: json['definition_id'],
    error: !exists(json, 'error') ? undefined : json['error'],
    published: json['published'],
    status_lists: !exists(json, 'status_lists')
      ? undefined
      : json['status_lists'],
  };
}

export function PublishStatusListResponseToJSON(
  value?: PublishStatusListResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    definition_id: value.definition_id,
    error: value.error,
    published: value.published,
    status_lists: value.status_lists,
  };
}
