/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agency Service
 *
 * The version of the OpenAPI document: v0.6.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface QueryResult
 */
export interface QueryResult {
  /**
   * Query results keyed by protocol
   * @type {{ [key: string]: object; }}
   * @memberof QueryResult
   */
  results?: { [key: string]: object };
}

export function QueryResultFromJSON(json: any): QueryResult {
  return QueryResultFromJSONTyped(json, false);
}

export function QueryResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QueryResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    results: !exists(json, 'results') ? undefined : json['results'],
  };
}

export function QueryResultToJSON(value?: QueryResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    results: value.results,
  };
}
