/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.6.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ResolutionResult
 */
export interface ResolutionResult {
  /**
   * DID Document
   * @type {object}
   * @memberof ResolutionResult
   */
  did_doc: object;
  /**
   * Resolution metadata
   * @type {object}
   * @memberof ResolutionResult
   */
  metadata: object;
}

export function ResolutionResultFromJSON(json: any): ResolutionResult {
  return ResolutionResultFromJSONTyped(json, false);
}

export function ResolutionResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResolutionResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    did_doc: json['did_doc'],
    metadata: json['metadata'],
  };
}

export function ResolutionResultToJSON(value?: ResolutionResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    did_doc: value.did_doc,
    metadata: value.metadata,
  };
}
