/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SDJWSCreate
 */
export interface SDJWSCreate {
  /**
   * DID of interest
   * @type {string}
   * @memberof SDJWSCreate
   */
  did?: string;
  /**
   *
   * @type {object}
   * @memberof SDJWSCreate
   */
  headers?: object;
  /**
   *
   * @type {Array<string>}
   * @memberof SDJWSCreate
   */
  non_sd_list?: Array<string>;
  /**
   *
   * @type {object}
   * @memberof SDJWSCreate
   */
  payload: object;
  /**
   * Information used for proof verification
   * @type {string}
   * @memberof SDJWSCreate
   */
  verificationMethod?: string;
}

export function SDJWSCreateFromJSON(json: any): SDJWSCreate {
  return SDJWSCreateFromJSONTyped(json, false);
}

export function SDJWSCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SDJWSCreate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    did: !exists(json, 'did') ? undefined : json['did'],
    headers: !exists(json, 'headers') ? undefined : json['headers'],
    non_sd_list: !exists(json, 'non_sd_list') ? undefined : json['non_sd_list'],
    payload: json['payload'],
    verificationMethod: !exists(json, 'verificationMethod')
      ? undefined
      : json['verificationMethod'],
  };
}

export function SDJWSCreateToJSON(value?: SDJWSCreate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    did: value.did,
    headers: value.headers,
    non_sd_list: value.non_sd_list,
    payload: value.payload,
    verificationMethod: value.verificationMethod,
  };
}
