/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Service
 */
export interface Service {
  /**
   * Service ID
   * @type {string}
   * @memberof Service
   */
  id: string;
  /**
   * Array of Service endpoints
   * @type {Array<string>}
   * @memberof Service
   */
  serviceEndpoint: Array<string>;
  /**
   * Service Type
   * @type {string}
   * @memberof Service
   */
  type: string;
}

export function ServiceFromJSON(json: any): Service {
  return ServiceFromJSONTyped(json, false);
}

export function ServiceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Service {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    serviceEndpoint: json['serviceEndpoint'],
    type: json['type'],
  };
}

export function ServiceToJSON(value?: Service | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    serviceEndpoint: value.serviceEndpoint,
    type: value.type,
  };
}
