/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v100.0.100
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ServiceDecorator
 */
export interface ServiceDecorator {
  /**
   * List of recipient keys
   * @type {Array<string>}
   * @memberof ServiceDecorator
   */
  recipientKeys: Array<string>;
  /**
   * List of routing keys
   * @type {Array<string>}
   * @memberof ServiceDecorator
   */
  routingKeys?: Array<string>;
  /**
   * Service endpoint at which to reach this agent
   * @type {string}
   * @memberof ServiceDecorator
   */
  serviceEndpoint: string;
}

export function ServiceDecoratorFromJSON(json: any): ServiceDecorator {
  return ServiceDecoratorFromJSONTyped(json, false);
}

export function ServiceDecoratorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ServiceDecorator {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    recipientKeys: json['recipientKeys'],
    routingKeys: !exists(json, 'routingKeys') ? undefined : json['routingKeys'],
    serviceEndpoint: json['serviceEndpoint'],
  };
}

export function ServiceDecoratorToJSON(value?: ServiceDecorator | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    recipientKeys: value.recipientKeys,
    routingKeys: value.routingKeys,
    serviceEndpoint: value.serviceEndpoint,
  };
}
