/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StatusListCred
 */
export interface StatusListCred {
  /**
   * Status assigned
   * @type {boolean}
   * @memberof StatusListCred
   */
  assigned?: boolean;
  /**
   * Status list index
   * @type {number}
   * @memberof StatusListCred
   */
  index?: number;
  /**
   * Status list number
   * @type {number}
   * @memberof StatusListCred
   */
  list?: number;
  /**
   * Status bitstring
   * @type {string}
   * @memberof StatusListCred
   */
  status?: string;
}

export function StatusListCredFromJSON(json: any): StatusListCred {
  return StatusListCredFromJSONTyped(json, false);
}

export function StatusListCredFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StatusListCred {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    assigned: !exists(json, 'assigned') ? undefined : json['assigned'],
    index: !exists(json, 'index') ? undefined : json['index'],
    list: !exists(json, 'list') ? undefined : json['list'],
    status: !exists(json, 'status') ? undefined : json['status'],
  };
}

export function StatusListCredToJSON(value?: StatusListCred | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    assigned: value.assigned,
    index: value.index,
    list: value.list,
    status: value.status,
  };
}
