/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateStatusListCredRequest
 */
export interface UpdateStatusListCredRequest {
  /**
   * Status bitstring
   * @type {string}
   * @memberof UpdateStatusListCredRequest
   */
  status?: string;
}

export function UpdateStatusListCredRequestFromJSON(
  json: any,
): UpdateStatusListCredRequest {
  return UpdateStatusListCredRequestFromJSONTyped(json, false);
}

export function UpdateStatusListCredRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateStatusListCredRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, 'status') ? undefined : json['status'],
  };
}

export function UpdateStatusListCredRequestToJSON(
  value?: UpdateStatusListCredRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
  };
}
