/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateStatusListDefRequest
 */
export interface UpdateStatusListDefRequest {
  /**
   * Issuer DID for the status list
   * @type {string}
   * @memberof UpdateStatusListDefRequest
   */
  issuer_did?: string;
  /**
   * Status list type: 'w3c', 'ietf' or none
   * @type {string}
   * @memberof UpdateStatusListDefRequest
   */
  list_type?: string;
  /**
   * Issuer DID for the status list
   * @type {string}
   * @memberof UpdateStatusListDefRequest
   */
  verification_method?: string;
}

export function UpdateStatusListDefRequestFromJSON(
  json: any,
): UpdateStatusListDefRequest {
  return UpdateStatusListDefRequestFromJSONTyped(json, false);
}

export function UpdateStatusListDefRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateStatusListDefRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    issuer_did: !exists(json, 'issuer_did') ? undefined : json['issuer_did'],
    list_type: !exists(json, 'list_type') ? undefined : json['list_type'],
    verification_method: !exists(json, 'verification_method')
      ? undefined
      : json['verification_method'],
  };
}

export function UpdateStatusListDefRequestToJSON(
  value?: UpdateStatusListDefRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    issuer_did: value.issuer_did,
    list_type: value.list_type,
    verification_method: value.verification_method,
  };
}
