/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.11.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateOID4VPPresDefRequest
 */
export interface UpdateOID4VPPresDefRequest {
  /**
   * The presentation definition
   * @type {{ [key: string]: object; }}
   * @memberof UpdateOID4VPPresDefRequest
   */
  pres_def: { [key: string]: object };
}

export function UpdateOID4VPPresDefRequestFromJSON(
  json: any,
): UpdateOID4VPPresDefRequest {
  return UpdateOID4VPPresDefRequestFromJSONTyped(json, false);
}

export function UpdateOID4VPPresDefRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateOID4VPPresDefRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    pres_def: json['pres_def'],
  };
}

export function UpdateOID4VPPresDefRequestToJSON(
  value?: UpdateOID4VPPresDefRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    pres_def: value.pres_def,
  };
}
