/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.10.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface V10CredentialIssueRequest
 */
export interface V10CredentialIssueRequest {
  /**
   * Human-readable comment
   * @type {string}
   * @memberof V10CredentialIssueRequest
   */
  comment?: string | null;
}

export function V10CredentialIssueRequestFromJSON(
  json: any,
): V10CredentialIssueRequest {
  return V10CredentialIssueRequestFromJSONTyped(json, false);
}

export function V10CredentialIssueRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V10CredentialIssueRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    comment: !exists(json, 'comment') ? undefined : json['comment'],
  };
}

export function V10CredentialIssueRequestToJSON(
  value?: V10CredentialIssueRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    comment: value.comment,
  };
}
