/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.9.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface V20CredRequestRequest
 */
export interface V20CredRequestRequest {
  /**
   * Whether to remove the credential exchange record on completion (overrides --preserve-exchange-records configuration setting)
   * @type {boolean}
   * @memberof V20CredRequestRequest
   */
  auto_remove?: boolean;
  /**
   * Holder DID to substitute for the credentialSubject.id
   * @type {string}
   * @memberof V20CredRequestRequest
   */
  holder_did?: string | null;
}

export function V20CredRequestRequestFromJSON(
  json: any,
): V20CredRequestRequest {
  return V20CredRequestRequestFromJSONTyped(json, false);
}

export function V20CredRequestRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V20CredRequestRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    auto_remove: !exists(json, 'auto_remove') ? undefined : json['auto_remove'],
    holder_did: !exists(json, 'holder_did') ? undefined : json['holder_did'],
  };
}

export function V20CredRequestRequestToJSON(
  value?: V20CredRequestRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    auto_remove: value.auto_remove,
    holder_did: value.holder_did,
  };
}
