/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.7.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  LDProofVCDetail,
  LDProofVCDetailFromJSON,
  LDProofVCDetailFromJSONTyped,
  LDProofVCDetailToJSON,
  V20CredFilterIndy,
  V20CredFilterIndyFromJSON,
  V20CredFilterIndyFromJSONTyped,
  V20CredFilterIndyToJSON,
} from './';

/**
 *
 * @export
 * @interface V20CredFilter
 */
export interface V20CredFilter {
  /**
   * Credential filter for indy
   * @type {V20CredFilterIndy}
   * @memberof V20CredFilter
   */
  indy?: V20CredFilterIndy;
  /**
   * Credential filter for linked data proof
   * @type {LDProofVCDetail}
   * @memberof V20CredFilter
   */
  ld_proof?: LDProofVCDetail;
}

export function V20CredFilterFromJSON(json: any): V20CredFilter {
  return V20CredFilterFromJSONTyped(json, false);
}

export function V20CredFilterFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V20CredFilter {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    indy: !exists(json, 'indy')
      ? undefined
      : V20CredFilterIndyFromJSON(json['indy']),
    ld_proof: !exists(json, 'ld_proof')
      ? undefined
      : LDProofVCDetailFromJSON(json['ld_proof']),
  };
}

export function V20CredFilterToJSON(value?: V20CredFilter | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    indy: V20CredFilterIndyToJSON(value.indy),
    ld_proof: LDProofVCDetailToJSON(value.ld_proof),
  };
}
