/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.6.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface V20CredAttrSpec
 */
export interface V20CredAttrSpec {
  /**
   * MIME type: omit for (null) default
   * @type {string}
   * @memberof V20CredAttrSpec
   */
  mime_type?: string | null;
  /**
   * Attribute name
   * @type {string}
   * @memberof V20CredAttrSpec
   */
  name: string;
  /**
   * Attribute value: base64-encode if MIME type is present
   * @type {string}
   * @memberof V20CredAttrSpec
   */
  value: string;
}

export function V20CredAttrSpecFromJSON(json: any): V20CredAttrSpec {
  return V20CredAttrSpecFromJSONTyped(json, false);
}

export function V20CredAttrSpecFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): V20CredAttrSpec {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    mime_type: !exists(json, 'mime-type') ? undefined : json['mime-type'],
    name: json['name'],
    value: json['value'],
  };
}

export function V20CredAttrSpecToJSON(value?: V20CredAttrSpec | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    'mime-type': value.mime_type,
    name: value.name,
    value: value.value,
  };
}
