/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v0.6.8
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  VCRecord,
  VCRecordFromJSON,
  VCRecordFromJSONTyped,
  VCRecordToJSON,
} from './';

/**
 *
 * @export
 * @interface VCRecordList
 */
export interface VCRecordList {
  /**
   *
   * @type {Array<VCRecord>}
   * @memberof VCRecordList
   */
  results?: Array<VCRecord>;
}

export function VCRecordListFromJSON(json: any): VCRecordList {
  return VCRecordListFromJSONTyped(json, false);
}

export function VCRecordListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VCRecordList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    results: !exists(json, 'results')
      ? undefined
      : (json['results'] as Array<any>).map(VCRecordFromJSON),
  };
}

export function VCRecordListToJSON(value?: VCRecordList | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    results:
      value.results === undefined
        ? undefined
        : (value.results as Array<any>).map(VCRecordToJSON),
  };
}
