/**
 * Sudo Decentralized Identity Cloud Agent SDK
 * Provides REST API wrappers for Typescript Agent Controllers using the Sudo Decentralized Identity Cloud Agent Service
 *
 * The version of the OpenAPI document: v100.0.100
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  CreateDIDJWKRequest,
  CreateDIDJWKRequestFromJSON,
  CreateDIDJWKRequestToJSON,
  CreateDIDJWKResponse,
  CreateDIDJWKResponseFromJSON,
  CreateDIDJWKResponseToJSON,
} from '../models';

export interface DidJwkCreatePostRequest {
  body?: CreateDIDJWKRequest;
}

/**
 *
 */
export class DidApi extends runtime.BaseAPI {
  /**
   * Create DID JWK.
   */
  async didJwkCreatePostRaw(
    requestParameters: DidJwkCreatePostRequest,
  ): Promise<runtime.ApiResponse<CreateDIDJWKResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request({
      path: `/did/jwk/create`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateDIDJWKRequestToJSON(requestParameters.body),
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateDIDJWKResponseFromJSON(jsonValue),
    );
  }

  /**
   * Create DID JWK.
   */
  async didJwkCreatePost(
    requestParameters: DidJwkCreatePostRequest,
  ): Promise<CreateDIDJWKResponse> {
    const response = await this.didJwkCreatePostRaw(requestParameters);
    return await response.value();
  }
}
